### ISSUE TITLE
Solicitar ao Raphael Acesso total do Quadro para o André

### ISSUE THREAD

**Issue by aaugustogv** [bancodobrasil/featws#15]

**Comment by ralphg6** [comment]
<img width="1237" alt="Screen Shot 2022-03-28 at 11 44 08" src="https://user-images.githubusercontent.com/12281906/160423976-917df951-c42c-4b15-8fb5-3675b4548d22.png">

@aaugustogv você já estava com o acesso admin ao quadro! Tem alguma funcionalidade que não conseguiu acessar?
